{
  Throwable cause=e.getCause();
  logger.warn("exceptionCaught() UnexpectedError happened. Caused:{}",cause.getMessage(),cause);
}
