{
  try {
    processBean(beanName,result);
  }
 catch (  Throwable t) {
    logger.warn("Unexpected exception",t);
  }
}
