{
  try {
    nimm.testInvoke();
  }
 catch (  Exception e) {
    throw new RuntimeException(e);
  }
  return "OK";
}
